version: '3.0'

networks:

    network-distributed-systems-project:
        ipam:
            config:
                - subnet: 10.100.0.0/24

services:
    
    database-mongodb:
        image: 'mongo'
        volumes:
            - data:/data/db
        restart: always
        networks:
            mynetwork:
                ipv4_address: 10.100.0.200

    server-nginx-dhaka:
        build: server-nginx
        depends_on:
            - service-ride-sharing-dhaka
            - service-rating
        environment:
            - RIDE_SHARING_VARIABLE=service-ride-sharing-dhaka
        command: /bin/sh -c "envsubst < /etc/server-nginx/conf.d/server-nginx.conf.template > /etc/server-nginx/conf.d/server-nginx.conf && server-nginx -g 'daemon off;'"
        restart: always
        networks:
            mynetwork:
                ipv4_address: 10.100.0.2

    service-rating:
        build: service-rating
        depends_on:
            - database-mongodb
        restart: always
        networks:
            mynetwork:
                ipv4_address: 10.100.0.100

    server-nginx-ctg:
        build: server-nginx
        depends_on:
            - service-ride-sharing-ctg
            - service-rating
        environment:
            - RIDE_SHARING_VARIABLE=service-ride-sharing-ctg
        command: /bin/sh -c "envsubst < /etc/server-nginx/conf.d/server-nginx.conf.template > /etc/server-nginx/conf.d/server-nginx.conf && server-nginx -g 'daemon off;'"
        restart: always
        networks:
            mynetwork:
                ipv4_address: 10.100.0.20

    service-communication-dhaka:
        build: service-communication
        restart: always
        ports: 
            - 8080
        environment:
            - SERVER_LOCATION=dhaka
        networks:
            mynetwork:
                ipv4_address: 10.100.0.3

    service-communication-ctg:
        build: service-communication
        restart: always
        ports: 
            - 8080
        environment:
            - SERVER_LOCATION=chittagong
        networks:
            mynetwork:
                ipv4_address: 10.100.0.30

    service-ride-sharing-dhaka:
        build: service-ride-sharing
        depends_on: 
            - service-communication-dhaka
        environment:
            - SERVER_LOCATION=dhaka
        restart: always
        networks:
            mynetwork:
                ipv4_address: 10.100.0.4

    service-ride-sharing-ctg:
        build: service-ride-sharing
        restart: always
        depends_on: 
            - service-communication-ctg
        environment:
            - SERVER_LOCATION=chittagong
        networks:
            mynetwork:
                ipv4_address: 10.100.0.40


volumes:
    
    data:
